import {drawWarmaKnot,visualTension} from './warma-knot';
import {seeded,level,projectProgress} from './itaca-store';
import type {RenderState} from './world-renderer';
type V=[number,number,number];
const colors={FOCUS:[158,206,183],REFLECTION:[213,194,156],CREATIVITY:[160,191,215],REST:[157,180,173],PROGRESS:[178,211,185]};
function rotate(p:V,rx:number,ry:number,rz:number):V{let[x,y,z]=p;[y,z]=[y*Math.cos(rx)-z*Math.sin(rx),y*Math.sin(rx)+z*Math.cos(rx)];[x,z]=[x*Math.cos(ry)+z*Math.sin(ry),-x*Math.sin(ry)+z*Math.cos(ry)];return [x*Math.cos(rz)-y*Math.sin(rz),x*Math.sin(rz)+y*Math.cos(rz),z];}
export function startEssentialScene(canvas:HTMLCanvasElement,get:()=>RenderState){const ctx=canvas.getContext('2d');if(!ctx)return ()=>{};let frame=0,last=0,time=0,opening=.52,region=get().region,travel=1;const previous=document.createElement('canvas'),prior=previous.getContext('2d');
 const line=(x:number,y:number,rx:number,ry:number,a:number,color:string)=>{ctx.beginPath();ctx.ellipse(x,y,rx,ry,a,0,Math.PI*2);ctx.strokeStyle=color;ctx.lineWidth=.7;ctx.stroke();};
 const orb=(x:number,y:number,r:number,color:string)=>{const g=ctx.createRadialGradient(x-r*.34,y-r*.36,r*.05,x,y,r);g.addColorStop(0,'#cfe0c3');g.addColorStop(.15,color);g.addColorStop(.5,'#264b43');g.addColorStop(.88,'#16342e');g.addColorStop(1,'#728e78');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();};
 const render=(now:number)=>{frame=requestAnimationFrame(render);const p=get();if(document.hidden||['mirror','garden','body','art','settings','support'].includes(p.region))return;if(now-last<(p.reduced?150:33))return;const dt=Math.min(.1,(now-last)/1000);last=now;if(p.region!==region){previous.width=canvas.width;previous.height=canvas.height;prior?.drawImage(canvas,0,0);region=p.region;travel=p.reduced?1:0;}travel=Math.min(1,travel+dt/1.05);time+=p.reduced?0:dt*(p.region==='focus'?.006:p.mood==='REST'?.018:.045);const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio,1.5);if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.globalAlpha=1;if(travel<1&&previous.width){const t=1-Math.pow(1-travel,3);ctx.save();ctx.globalAlpha=1-t;ctx.translate(w*.65,h*.46);ctx.scale(1+t*1.8,1+t*1.8);ctx.drawImage(previous,-w*.65,-h*.46,w,h);ctx.restore();ctx.globalAlpha=t;ctx.translate(w*.5*(1-t)*.15,h*.5*(1-t)*.15);ctx.scale(.85+t*.15,.85+t*.15);}const mobile=window.innerWidth<768,r=Math.min(w*(p.region==='world'?.29:mobile?.32:.165),h*(p.region==='world'?.26:.285)),cx=w*(p.region==='world'?.5:mobile?.5:w<1000?.73:.65),cy=h*(p.region==='world'?.43:mobile?.42:.465),rand=seeded(p.data.seed||7854);const col=colors[p.mood];const o=visualTension(p.data)+(p.hover?.04:0);opening+=(o-opening)*(p.reduced?1:.065);
 if(p.region!=='world'&&p.region!=='story'){
  if(p.region==='focus'){const x=w*.5,y=h*.47;for(let i=0;i<8;i++)line(x,y,110+i*55,160+i*74,Math.sin(time)*.05,`rgba(148,182,169,${.28-i*.02})`);const grow=.2+p.focusProgress*.65;orb(x,y,r*grow*.55,'#92b69c');if(p.focusProgress>=.25)for(let i=0;i<Math.floor(p.focusProgress*36);i++){const a=i*2.399,rr=r*(.6+(i%3)*.12);ctx.fillStyle='#bbd4b6';ctx.fillRect(x+Math.cos(a)*rr,y+Math.sin(a)*rr,2,2);}}
  else if(p.region==='projects'){p.data.projects.slice(0,3).forEach((project,i)=>{const x=w*(.23+i*.27),y=h*.45,rad=Math.min(w*.095,95),prog=projectProgress(project)/100;orb(x,y,rad,project.color);for(let j=0;j<4;j++)line(x,y,rad*1.1,rad*(.3+j*.15),.5,project.color+'44');ctx.beginPath();ctx.ellipse(x,y,rad*1.27,rad*.48,.5,-Math.PI/2,-Math.PI/2+Math.PI*2*prog);ctx.lineWidth=2;ctx.strokeStyle=project.color;ctx.stroke();if(!prog){ctx.fillStyle='#0a172abb';ctx.beginPath();ctx.arc(x,y,rad,0,7);ctx.fill();for(let j=0;j<4;j++)line(x,y,rad,rad*(.15+j*.22),0,project.color+'66');}});}
  else if(p.region==='memory'){const x=w*.75,y=h*.45;for(let i=0;i<6;i++){const size=110+i*80;ctx.strokeStyle=`rgba(170,178,152,${.13+i*.015})`;ctx.beginPath();ctx.moveTo(x-size,y+size);ctx.lineTo(x-size,y-size*.45);ctx.quadraticCurveTo(x,y-size*1.4,x+size,y-size*.45);ctx.lineTo(x+size,y+size);ctx.stroke();}p.data.knowledge.slice(0,50).forEach((k,i)=>{const a=rand()*6.28,rr=rand()*r*1.5;ctx.fillStyle=k.kind==='flashcard'?'#d4c89d':'#9dc1b0';ctx.beginPath();ctx.arc(x+Math.cos(a)*rr,y+Math.sin(a)*rr,2+Math.min(3,k.reviews*.2),0,7);ctx.fill();});}
  else if(p.region==='journal'){const x=w*.65,y=h*.5;line(x,y,r*1.5,r*.8,-.4,'#c8bc9850');p.data.journal.slice(0,100).forEach((j,i)=>{const a=rand()*6.28,rr=r*(.5+rand()*1.4);const px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;ctx.strokeStyle=j.unlockDate?'#b3b8d7':'#dcc194';ctx.beginPath();ctx.moveTo(px-4,py);ctx.lineTo(px+4,py);ctx.moveTo(px,py-4);ctx.lineTo(px,py+4);ctx.stroke();});}
  else if(p.region==='observatory'){for(let i=0;i<4;i++)line(w*.84,h*.3,r*(1.3+i*.17),r*(.8+i*.12),-.7,'#8aacb535');}
  else if(p.region==='path'){const x=w*.5,y=h*.4;line(x,y,r*1.3,r*.8,-.1,'#b5c4a445');p.data.events.slice(-70).forEach((e,i)=>{const a=i*.3,rr=70+i*3;ctx.fillStyle=e.type==='journal_entry_created'?'#dac49a':'#b5cda6';ctx.beginPath();ctx.arc(x+Math.cos(a)*rr,y+Math.sin(a)*rr*.6,2,0,7);ctx.fill();});}
  return;
 }
 const aura=ctx.createRadialGradient(cx,cy,0,cx,cy,r*1.8);aura.addColorStop(0,'#56796717');aura.addColorStop(1,'#080f1500');ctx.fillStyle=aura;ctx.fillRect(0,0,w,h);
 for(let i=0;i<3;i++)line(cx,cy,r*(1.35+i*.1),r*(.45+i*.21),-.5+i*.75+time*.2,i===1?'#c9bf8c38':'#97b9a42f');
 drawWarmaKnot(ctx,cx,cy,r*.91,opening,time);
 p.data.subjects.slice(0,9).forEach((subject,i)=>{const a=i*2.399,rr=r*(1.45+(i%2)*.1),x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr*.78;ctx.strokeStyle=subject.color+'70';ctx.fillStyle=subject.color;ctx.beginPath();ctx.moveTo(x-8,y+4);ctx.lineTo(x,y-7);ctx.lineTo(x+11,y+1);ctx.stroke();for(const [dx,dy] of [[-8,4],[0,-7],[11,1]]){ctx.beginPath();ctx.arc(x+dx,y+dy,1.5,0,7);ctx.fill();}});
 p.data.projects.filter(x=>projectProgress(x)===100).slice(0,10).forEach((project,i)=>{const a=i*2.399+.5,x=cx+Math.cos(a)*r*1.32,y=cy+Math.sin(a)*r*.75;ctx.strokeStyle=project.color;ctx.fillStyle=project.color+'66';ctx.beginPath();ctx.moveTo(x,y-12);ctx.lineTo(x+5,y+2);ctx.lineTo(x,y+6);ctx.lineTo(x-5,y+2);ctx.closePath();ctx.fill();ctx.stroke();});
 const types=[{list:p.data.missions.filter(x=>x.done),color:'#c9d6a0'},{list:p.data.journal,color:'#e5c79a'},{list:p.data.sessions.filter(s=>s.seconds>=60),color:'#aad1c1'}];for(const type of types){type.list.slice(0,80).forEach((_,i)=>{const a=rand()*7,rr=r*(1.3+rand()*.3),x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr*.8;ctx.fillStyle=type.color;ctx.beginPath();ctx.arc(x,y,1.5+rand(),0,7);ctx.fill();});}
 };frame=requestAnimationFrame(render);return ()=>cancelAnimationFrame(frame);
}
