import type {InstrumentLegalStatus,ScoringProtocol} from './psychometric-engine';
import {pss10Metadata,pss10Protocol} from './pss10-instrument';
export type InstrumentId='asq14'|'sisco21'|'pss10'|'pss14'|'essa'|'mslq';
export type Instrument={legalStatus:InstrumentLegalStatus;accessObtained:boolean;version:string|null;language:string|null;ageRange:readonly [number,number]|null;copyright:string;scoringProtocol:ScoringProtocol|null;id:InstrumentId;name:string;authors:string;year:number;itemCount:number;measures:string;population:string;evidence:string;source:string;doi:string;permission:string;limitations:string;licensed:boolean;populationReviewed:boolean;translationReviewed:boolean;scoringReviewed:boolean;itemsVerified:boolean};
// Metadata only. No copyrighted items, norms, responses or diagnostic cut-offs.
const pending={legalStatus:'PENDING_PERMISSION' as const,accessObtained:false,version:null,language:null,ageRange:null,copyright:'Titular y alcance pendientes de verificar.',scoringProtocol:null,licensed:false,populationReviewed:false,translationReviewed:false,scoringReviewed:false,itemsVerified:false};
export const instruments:readonly Instrument[]=[
 {...pending,id:'asq14',name:'ASQ-14',authors:'María J. Blanca, Milagros Escobar, Juan F. Lima, Donald Byrne y Rafael Alarcón',year:2020,itemCount:14,measures:'Estresores cotidianos acumulados en la adolescencia. Una única dimensión.',population:'España: 561 estudiantes de 12–18 años. Perú: resumen aceptado de 982 escolares de 12–17 años.',evidence:'España: alfa .85 y test-retest .81. Perú (2026): alfa y omega .85; CFI/TLI .96, RMSEA .08, SRMR .07.',source:'https://www.psicothema.com/pdf/4601.pdf',doi:'10.7334/psicothema2019.288',permission:'© 2020 Psicothema. No se ha verificado una licencia que autorice los ítems y su versión española en WARMA. El CC BY del artículo peruano no acredita ese permiso.',limitations:'No mide por separado afrontamiento, síntomas o autorregulación. El artículo peruano aún anuncia su texto final como pendiente; no hay baremos COAR. Invariancia regional parcial y límites de ajuste IRT.'},
 {...pending,id:'sisco21',name:'SISCO SV-21',authors:'Arturo Barraza Macías',year:2018,itemCount:21,measures:'Estresores académicos, síntomas y estrategias de afrontamiento.',population:'Manual: muestra mixta mexicana de bachillerato y universidad. Perú: 560 universitarios de 18–50 años.',evidence:'Perú (2021): tres factores correlacionados, omega .90/.89/.89; CFI .929, TLI .920, RMSEA .083, SRMR .061.',source:'https://doi.org/10.20511/pyr2021.v9n2.647',doi:'10.20511/pyr2021.v9n2.647',permission:'El manual reserva derechos; los autores del estudio peruano solicitaron permiso. Falta autorización digital de WARMA.',limitations:'La evidencia universitaria peruana no establece baremos de secundaria. Los reactivos de filtro no se confunden con los 21 principales; no se han incorporado ítems ni puntos de corte.'},
 {...pending,accessObtained:true,version:pss10Metadata.version,language:pss10Metadata.language,copyright:pss10Metadata.copyright,scoringProtocol:pss10Protocol,id:'pss10',name:'PSS-10',authors:'Sheldon Cohen y Gail M. Williamson (versión abreviada)',year:1988,itemCount:10,measures:'Estrés percibido global del último mes; no sólo presión académica.',population:'Referencia original estadounidense; revisar la adaptación exacta para adolescentes peruanos.',evidence:'Paquete oficial Spanish for Spain de ePROVIDE recibido y verificado; no incluye un estudio de validación de esta versión exacta en adolescentes peruanos.',source:'https://www.cmu.edu/dietrich/psychology/stress-immunity-disease-lab/scales/index.html',doi:'10.24265/liberabit.2025.v31n1.1047',permission:'Acceso al paquete obtenido; © RST Assessments, LLC (2022). El manual exige contactar a Mapi antes del uso. Administración electrónica y redistribución pública pendientes de acuerdo verificable.',limitations:'CMU indica que no es diagnóstica y no tiene puntos de corte. EPGE-13 peruana no equivale a PSS-10.'},
 {...pending,id:'pss14',name:'PSS-14',authors:'Sheldon Cohen, Tom Kamarck y Robin Mermelstein',year:1983,itemCount:14,measures:'Estrés percibido global.',population:'Adaptación peruana: 332 universitarios de Beca 18, de 16–25 años; retuvo 13 ítems.',evidence:'Guzmán-Yacaman y Reyes-Bossio (2018): EPGE-13 con dos dimensiones, alfa .79/.77. Estos coeficientes no corresponden a PSS-14.',source:'https://doi.org/10.18800/psico.201802.012',doi:'10.18800/psico.201802.012',permission:'Permiso del instrumento y de la traducción concreta pendientes; gestión indicada por CMU.',limitations:'No confundir EPGE-13 con PSS-14 ni transferir evidencia universitaria a COAR. Sin umbrales diagnósticos.'},
 {...pending,id:'essa',name:'ESSA',authors:'Jiandong Sun, Michael P. Dunne, Xiang-yu Hou y Ai-qiang Xu',year:2011,itemCount:16,measures:'Estrés educativo: presión, carga, preocupación por notas, autoexpectativas y desaliento.',population:'Desarrollo con más de 2.000 adolescentes chinos. Validación griega: 399 escolares, edad media 16.3.',evidence:'Estudio original: cinco factores y 64% de varianza explicada. Moustaka y colaboradores (2023): alfa total .878.',source:'https://doi.org/10.1177/0734282910394976',doi:'10.1177/0734282910394976',permission:'SAGE muestra acceso restringido y trámite de reutilización. Derechos de escala y traducción española sin confirmar.',limitations:'No se verificó una adaptación española autorizada con evidencia en secundarios peruanos. No se importan normas chinas o griegas.'},
 {...pending,id:'mslq',name:'MSLQ',authors:'Paul R. Pintrich, David A. F. Smith, Teresa García y Wilbert J. McKeachie',year:1991,itemCount:81,measures:'Motivación y estrategias de aprendizaje autorregulado; no mide estrés.',population:'Manual original: 380 universitarios estadounidenses.',evidence:'Subescalas modulares; autorregulación metacognitiva: 12 ítems, alfa .79 en el manual.',source:'https://files.eric.ed.gov/fulltext/ED338122.pdf',doi:'',permission:'Manual disponible en ERIC; reproducción, traducción y versión para secundaria pendientes de verificar.',limitations:'Complementario, no sustituto de una escala de estrés. No se suman constructos distintos en un índice de salud.'}
];
export const principalCandidate=instruments.find(i=>i.id==='pss10')!;
export function administrationStatus(id:string){
 const instrument=instruments.find(i=>i.id===id);
 if(!instrument)return {available:false,reason:'Instrumento no registrado.'};
 const missing=[!instrument.licensed&&'autorización de uso',!instrument.populationReviewed&&'revisión de la población',!instrument.translationReviewed&&'traducción verificada',!instrument.scoringReviewed&&'corrección revisada',!instrument.itemsVerified&&'ítems verificados'].filter(Boolean);
 return {available:missing.length===0,reason:missing.length?'Pendiente: '+missing.join(', ')+'.':'Requisitos documentados.'};
}
