import {seeded,level,projectProgress,type WorldState,type Region,type Mood} from './itaca-store';
import {knotSurface,visualTension} from './warma-knot';
type V=[number,number,number];type M=Float32Array;
const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
function mul(a:M,b:M){const out=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)out[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return out;}
const sub=(a:V,b:V):V=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
const norm=(v:V):V=>{const n=Math.hypot(...v)||1;return v.map(x=>x/n) as V;};
const cross=(a:V,b:V):V=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const dot=(a:V,b:V)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
function transform(pos:V=[0,0,0],scale:V=[1,1,1],rotation:V=[0,0,0]){const m=I();m[12]=pos[0];m[13]=pos[1];m[14]=pos[2];const rx=I(),ry=I(),rz=I();const [x,y,z]=rotation;rx[5]=Math.cos(x);rx[6]=Math.sin(x);rx[9]=-Math.sin(x);rx[10]=Math.cos(x);ry[0]=Math.cos(y);ry[2]=-Math.sin(y);ry[8]=Math.sin(y);ry[10]=Math.cos(y);rz[0]=Math.cos(z);rz[1]=Math.sin(z);rz[4]=-Math.sin(z);rz[5]=Math.cos(z);const sm=I();sm[0]=scale[0];sm[5]=scale[1];sm[10]=scale[2];return mul(m,mul(rz,mul(ry,mul(rx,sm))));}
function projection(aspect:number){const f=1/Math.tan(38*Math.PI/360),near=.1,far=100;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);}
function view(eye:V,at:V){const z=norm(sub(eye,at)),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
function rgb(hex:string):V{if(!/^#[0-9a-f]{6}$/i.test(hex))hex='#a0c9bc';return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255) as V;}
const vertex=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uModel;uniform mat4 uVP;uniform float uTime;uniform float uMorph;uniform float uKind;varying vec3 vNormal;varying vec3 vWorld;varying vec3 vLocal;void main(){vec3 p=aPosition;if(uKind>.5&&uKind<1.5){float n=sin(p.x*5.+uTime*.12)*sin(p.y*4.-uTime*.09)*sin(p.z*5.);p+=aNormal*n*.05*uMorph;}vec4 w=uModel*vec4(p,1.);vWorld=w.xyz;mat3 m=mat3(uModel);vNormal=normalize(aNormal.x*cross(m[1],m[2])+aNormal.y*cross(m[2],m[0])+aNormal.z*cross(m[0],m[1]));vLocal=p;gl_Position=uVP*w;}`;
const fragment=`precision highp float;uniform vec3 uColor;uniform vec3 uEye;uniform float uKind;uniform float uAlpha;uniform float uTime;varying vec3 vNormal;varying vec3 vWorld;varying vec3 vLocal;
vec3 environment(vec3 r){float a=pow(max(0.,dot(r,normalize(vec3(-.6,1.,1.2)))),18.);float b=pow(max(0.,dot(r,normalize(vec3(1.,.3,-1.)))),32.);float band=(1.-smoothstep(0.,.06,abs(r.y-.35)))*smoothstep(-.3,.4,r.x);return vec3(.05,.095,.09)+vec3(.93,1.,.9)*a*1.6+vec3(.3,.65,.65)*b+vec3(.6,.8,.7)*band*.6;}
void main(){if(uKind>2.5&&uKind<3.5){gl_FragColor=vec4(uColor,uAlpha);return;}vec3 n=normalize(vNormal);vec3 eye=normalize(uEye-vWorld);if(dot(n,eye)<0.)n=-n;float fres=pow(1.-max(0.,dot(n,eye)),3.);float lam=max(0.,dot(n,normalize(vec3(-.6,1.,1.))));vec3 reflectColor=environment(reflect(-eye,n));vec3 refractColor=environment(refract(-eye,n,.72));float spec=pow(max(0.,dot(reflect(normalize(vec3(.5,-1.,-1.)),n),eye)),40.);vec3 c=uColor*(.09+lam*.48)+reflectColor*.64+vec3(.7,.87,.72)*spec*.7;float alpha=uAlpha;if(uKind<.5||uKind>3.5){c=mix(c,refractColor+uColor*.16,.3)+uColor*fres*.32;float striation=sin(vLocal.y*28.+vLocal.x*5.)*.5+.5;c+=uColor*striation*.025;alpha=uAlpha+fres*.1;}else if(uKind<1.5){float band=sin(vLocal.y*22.+sin(vLocal.x*9.)+uTime*.08)*.5+.5;c=uColor*(.06+.09*band)+reflectColor*.35+uColor*fres*.7+spec*.6;}else{c=uColor*(.18+lam*.6)+reflectColor*.2;}c=c/(c+vec3(.65));c=pow(c,vec3(.88));gl_FragColor=vec4(c,alpha);}`;
interface Mesh{buffer:WebGLBuffer;normal:WebGLBuffer;count:number;mode:number;}
export interface RenderState {data:WorldState;region:Region;hover:Region|null;mood:Mood;reduced:boolean;focusProgress:number;storyProgress:number;onRegion:(r:Region)=>void;onProject:(id:string)=>void;onQuality:(s:string)=>void;}
export function createWorldRenderer(host:HTMLDivElement,get:()=>RenderState,quality:string,onFallback:()=>void){
 const canvas=document.createElement('canvas');canvas.setAttribute('aria-hidden','true');const context=canvas.getContext('webgl',{alpha:true,antialias:quality!=='balanced',premultipliedAlpha:false,powerPreference:'high-performance'});if(!context)throw new Error('WebGL unavailable');const gl:WebGLRenderingContext=context;
 function compile(type:number,code:string){const s=gl!.createShader(type)!;gl!.shaderSource(s,code);gl!.compileShader(s);if(!gl!.getShaderParameter(s,gl!.COMPILE_STATUS))throw new Error(gl!.getShaderInfoLog(s)||'Shader');return s;}
 const vs=compile(gl.VERTEX_SHADER,vertex),fs=compile(gl.FRAGMENT_SHADER,fragment),program=gl.createProgram()!;gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program)||'Program');gl.useProgram(program);host.appendChild(canvas);
 const uniform=(s:string)=>gl.getUniformLocation(program,s),aPos=gl.getAttribLocation(program,'aPosition'),aNorm=gl.getAttribLocation(program,'aNormal'),uModel=uniform('uModel'),uVP=uniform('uVP'),uTime=uniform('uTime'),uMorph=uniform('uMorph'),uKind=uniform('uKind'),uColor=uniform('uColor'),uAlpha=uniform('uAlpha'),uEye=uniform('uEye');
 const meshes:Mesh[]=[];
 function mesh(vertices:number[],normals:number[],mode:number=gl.TRIANGLES):Mesh{const buffer=gl.createBuffer()!,normal=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,normal);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(normals),gl.STATIC_DRAW);const m={buffer,normal,count:vertices.length/3,mode};meshes.push(m);return m;}
 function triangles(faces:V[][],smooth=false){const vs:number[]=[],ns:number[]=[];faces.forEach(f=>{const n=norm(cross(sub(f[1],f[0]),sub(f[2],f[0])));f.forEach(p=>{vs.push(...p);ns.push(...(smooth?norm(p):n));});});return mesh(vs,ns);}
 function octa(){const top:V=[0,1.6,0],bottom:V=[0,-.8,0],ring:V[]=[[.55,0,0],[0,0,.42],[-.55,0,0],[0,0,-.42]];return triangles(ring.flatMap((p,i)=>[[top,p,ring[(i+1)%4]],[bottom,ring[(i+1)%4],p]]));}
 function sphere(){const f:V[][]=[],N=36,M=24;const p=(i:number,j:number):V=>[Math.sin(j/M*Math.PI)*Math.cos(i/N*Math.PI*2),Math.cos(j/M*Math.PI),Math.sin(j/M*Math.PI)*Math.sin(i/N*Math.PI*2)];for(let j=0;j<M;j++)for(let i=0;i<N;i++){f.push([p(i,j),p(i+1,j),p(i,j+1)],[p(i+1,j),p(i+1,j+1),p(i,j+1)]);}return triangles(f,true);}
 function ringMesh(){const a:number[]=[],n:number[]=[];for(let i=0;i<180;i++){for(const ang of [i/180*6.283185,(i+1)/180*6.283185]){a.push(Math.cos(ang),Math.sin(ang),0);n.push(0,0,1);}}return mesh(a,n,gl.LINES);}
 function cone(){const faces:V[][]=[];for(let i=0;i<7;i++){const a=i/7*6.283185,b=(i+1)/7*6.283185;faces.push([[Math.cos(a),0,Math.sin(a)],[0,-1,0],[Math.cos(b),0,Math.sin(b)]],[[0,0,0],[Math.cos(a),0,Math.sin(a)],[Math.cos(b),0,Math.sin(b)]]);}return triangles(faces);}
 const crystal=octa(),ball=sphere(),ring=ringMesh(),land=cone();
 let knotTension=-1;const knot=mesh([],[]);
 function updateKnot(tension:number){if(Math.abs(tension-knotTension)<.004)return;knotTension=tension;const v:number[]=[],n:number[]=[],S=200,R=12;for(let i=0;i<S;i++)for(let j=0;j<R;j++){const a=knotSurface(i/S*6.283185,j/R*6.283185,tension),b=knotSurface((i+1)/S*6.283185,j/R*6.283185,tension),c=knotSurface((i+1)/S*6.283185,(j+1)/R*6.283185,tension),d=knotSurface(i/S*6.283185,(j+1)/R*6.283185,tension);for(const p of [a,b,c,a,c,d]){v.push(...p.p);n.push(...p.n);}}gl.bindBuffer(gl.ARRAY_BUFFER,knot.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.DYNAMIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,knot.normal);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(n),gl.DYNAMIC_DRAW);knot.count=v.length/3;}

 function draw(m:Mesh,model:M,color:V,kind=0,alpha=1){gl!.uniformMatrix4fv(uModel,false,model);gl!.uniform3fv(uColor,color);gl!.uniform1f(uKind,kind);gl!.uniform1f(uAlpha,alpha);gl!.bindBuffer(gl!.ARRAY_BUFFER,m.buffer);gl!.enableVertexAttribArray(aPos);gl!.vertexAttribPointer(aPos,3,gl!.FLOAT,false,0,0);gl!.bindBuffer(gl!.ARRAY_BUFFER,m.normal);gl!.enableVertexAttribArray(aNorm);gl!.vertexAttribPointer(aNorm,3,gl!.FLOAT,false,0,0);gl!.drawArrays(m.mode,0,m.count);}
 const reg:Record<string,V>={focus:[-3,1,-5],projects:[4,-1,-6],memory:[-5,-2,-8],journal:[0,4,-7],observatory:[6,4,-9],path:[0,-5,-8]};
 const cols:Record<Mood,V>={FOCUS:rgb('#96c8b5'),REFLECTION:rgb('#d4bb95'),CREATIVITY:rgb('#9ebed4'),REST:rgb('#99b2b0'),PROGRESS:rgb('#b2d3b9')};
 const random=seeded(get().data.seed||12);const shards=Array.from({length:28},(_,i)=>({a:(i>=18?(i-18)/10+.035:i/18)*Math.PI*2,z:i>=18?-.3:.05,size:i>=18?.26:.35+random()*.1,tilt:.12,r:i>=18?.85:1.12}));
 let mode=quality==='immersive'||quality==='auto'&&host.clientWidth>1000&&(navigator.hardwareConcurrency||4)>=6?'Immersive':'Balanced',ratio=Math.min(devicePixelRatio,mode==='Immersive'?1.7:1.15),frame=0,stopped=false,last=performance.now(),time=0,elapsed=0,frames=0,bad=0,orbit=0,drag=false,lastX=0,downX=0,downY=0,opening=1,lastDraw=0;let mouse:V=[0,0,0],current:V=[0,0,0],eye:V=[0,.1,10.5],look:V=[0,0,0],color=cols.PROGRESS.slice() as V;
 const resize=()=>{canvas.width=Math.floor(host.clientWidth*ratio);canvas.height=Math.floor(host.clientHeight*ratio);gl.viewport(0,0,canvas.width,canvas.height);};const observer=new ResizeObserver(resize);observer.observe(host);resize();get().onQuality(mode);
 const move=(e:PointerEvent)=>{const b=canvas.getBoundingClientRect();mouse=[(e.clientX-b.left)/b.width*2-1,1-(e.clientY-b.top)/b.height*2,0];if(drag){orbit+=(e.clientX-lastX)*.005;lastX=e.clientX;}};
 const down=(e:PointerEvent)=>{drag=true;downX=lastX=e.clientX;downY=e.clientY;};
 const up=()=>{drag=false;};
 canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerdown',down);window.addEventListener('pointerup',up);
 gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(0,0,0,0);
 function render(now:number){if(stopped)return;frame=requestAnimationFrame(render);if(document.hidden||['mirror','garden','body','art','settings','support'].includes(get().region)){last=now;return;}const dt=Math.min(.08,(now-last)/1000);last=now;const s=get(),mobile=window.innerWidth<768;if(s.reduced&&now-lastDraw<100)return;lastDraw=now;time+=s.reduced?0:dt*(s.region==='focus'?.05:s.mood==='REST'?.1:.5);const smooth=s.reduced?1:1-Math.exp(-dt*3.5);current=current.map((v,i)=>v+(mouse[i]-v)*smooth) as V;
  let targetEye:V=[0,.1,(s.region==='world'?8.8:mobile?10.5:host.clientWidth<1000?14:10.5)-s.storyProgress*3],targetLook:V=[0,0,-s.storyProgress*1.5];if(reg[s.region]){targetLook=reg[s.region];targetEye=[targetLook[0],targetLook[1]+.1,targetLook[2]+(s.region==='focus'?6:8.8)];}
  eye=eye.map((v,i)=>v+(targetEye[i]-v)*smooth) as V;look=look.map((v,i)=>v+(targetLook[i]-v)*smooth) as V;color=color.map((v,i)=>v+(cols[s.mood][i]-v)*smooth) as V;
  const vp=mul(projection(canvas.width/canvas.height),view(eye,[look[0]+current[0]*.1,look[1]+current[1]*.1,look[2]]));gl!.clear(gl!.COLOR_BUFFER_BIT|gl!.DEPTH_BUFFER_BIT);gl!.uniformMatrix4fv(uVP,false,vp);gl!.uniform3fv(uEye,eye);gl!.uniform1f(uTime,time);gl!.uniform1f(uMorph,s.mood==='CREATIVITY'?1:.35);
  const coreScale=s.region==='world'?1.25:mobile?1.2:host.clientWidth<1000?1.2:1.55;const base=transform([s.region==='world'?0:mobile?0:host.clientWidth<1000?2:1.55,s.region==='world'?.5:mobile?.5:.3,0],[coreScale,coreScale,coreScale],[.24,.5+Math.sin(time*.09)*.12+orbit,-.38+time*.01]);
  if(s.region==='world'||s.region==='story'||Math.hypot(...sub(eye,targetEye))>.2){
   const desired=visualTension(s.data)+(s.hover?.04:0);opening+=(desired-opening)*smooth;updateKnot(opening);
   draw(knot,mul(base,transform([0,0,0],[1,1,1],[.46,0,0])),rgb('#72c5b6'),4,1);
   for(let j=0;j<2;j++)draw(ring,mul(base,transform([0,0,0],[2.1+j*.18,2.1+j*.18,2.1+j*.18],[.7+j*.6,.2,0])),rgb('#80a99b'),3,.12);
   const rand=seeded(s.data.seed+71),lev=level(s.data);if(lev>=1)draw(land,mul(base,transform([0,-2,0],[1.2,.7,1.2])),rgb('#4a6c58'),2);
   for(let i=0;i<Math.min(80,s.data.missions.filter(m=>m.done).length);i++){const a=rand()*6.28,r=1.8+rand()*.8;draw(crystal,mul(base,transform([Math.cos(a)*r,(rand()-.5)*3,Math.sin(a)*r],[.055,.055,.055])),rgb('#bdd6a1'),3);}
   s.data.sessions.filter(x=>x.seconds>=60).slice(0,30).forEach((x,i)=>{const a=i*2.4,h=.12+Math.min(.4,x.seconds/3600);draw(crystal,mul(base,transform([Math.cos(a)*.9,-1.8+h,Math.sin(a)*.9],[.12,h,.12])),color,2);});
   s.data.journal.slice(0,80).forEach((j,i)=>{const a=rand()*6.28,r=2.8+rand()*.5;draw(crystal,mul(base,transform([Math.cos(a)*r,(rand()-.5)*3,Math.sin(a)*r],[.05,.05,.05])),rgb('#e3c58e'),3);});
   s.data.subjects.slice(0,12).forEach((su,i)=>{const a=i*2.4;draw(ring,mul(base,transform([Math.cos(a)*2.9,Math.sin(a)*2.5,0],[.2,.2,.2],[i,.5,0])),rgb(su.color),3,.5);});
   if(lev>=2)for(let i=0;i<lev*3;i++){const a=rand()*6.28;draw(crystal,mul(base,transform([Math.cos(a),-1.55,Math.sin(a)],[.11,.18+rand()*.16,.1],[0,a,.25])),rgb('#98bb95'),2);}
   s.data.projects.filter(p=>projectProgress(p)===100).slice(0,12).forEach((p,i)=>draw(crystal,mul(base,transform([Math.cos(i*2)*1.5,-1.15,Math.sin(i*2)*1.5],[.25,.4,.25])),rgb(p.color),0));
   if(lev>=4)for(let i=0;i<15;i++)draw(crystal,mul(base,transform([Math.cos(i)*1.3,-1.6,Math.sin(i)*1.3],[.15,.35+i%3*.15,.15])),color,2);
   if(lev>=5)for(let i=0;i<(lev===6?8:3);i++)draw(ball,mul(base,transform([Math.cos(i*2)*3.2,Math.sin(i*2)*2.8,Math.sin(i)*2],[.14,.14,.14])),color,1);
  }
  if(s.region==='focus'){const p=reg.focus;for(let i=0;i<8;i++){const opacity=s.focusProgress===0?.1:.1+s.focusProgress*.2;draw(ring,transform([p[0],p[1],p[2]-i*.7],[1.8+i*.18,1.8+i*.18,1],[0,0,i*.25+time*.02]),color,3,opacity);}const size=.2+s.focusProgress*.65;draw(ball,transform([p[0],p[1],p[2]-2],[size,size,size]),color,1);if(s.focusProgress>=.25)for(let i=0;i<12;i++){const a=i*.524;draw(crystal,transform([p[0]+Math.cos(a),p[1]+Math.sin(a),p[2]-2],[.035,.035,.035]),color,3,.6);}if(s.focusProgress>=.5)for(let i=0;i<6;i++)draw(crystal,transform([p[0]+Math.cos(i)*1.4,p[1]-.7,p[2]-2+Math.sin(i)],[.08,.4,.08]),color,2);if(s.focusProgress>=.75)for(let i=0;i<12;i++)draw(crystal,transform([p[0]+Math.cos(i)*1.8,p[1]-.5,p[2]-2+Math.sin(i)],[.15,.25,.15],[.1,i,.3]),rgb('#a4c399'),2);}
  if(s.region==='projects'){const p=reg.projects;s.data.projects.slice(0,9).forEach((pr,i)=>{const pos:V=[p[0]+(i%3-1)*2.2,p[1]+.5-Math.floor(i/3)*1.9,p[2]],progress=projectProgress(pr)/100;const col=rgb(pr.color);draw(ball,transform(pos,[.6,.6,.6],[0,time*.08,0]),col,progress===1?0:1,1);draw(ring,transform(pos,[.85,.85,.85],[.75,-.3,.4]),col,3,.35+progress*.6);for(let j=0;j<Math.ceil(progress*8);j++){const a=j*.785;draw(crystal,transform([pos[0]+Math.cos(a)*.64,pos[1]+Math.sin(a)*.64,pos[2]],[.07,.15,.07],[0,0,-a]),col,0);}});}
  if(s.region==='memory'){const p=reg.memory,col=rgb('#c9c3a5');for(let i=0;i<7;i++){draw(ring,transform([p[0],p[1],p[2]-i*1.1],[2.8,3.8,1],[0,0,0]),col,3,.17);for(const side of [-1,1])draw(crystal,transform([p[0]+side*2.5,p[1]-.4,p[2]-i*1.1],[.13,1.7,.13]),col,2);}const rand=seeded(s.data.seed+193);s.data.knowledge.slice(0,70).forEach(k=>{const a=rand()*6.28,r=.6+rand()*1.6;draw(crystal,transform([p[0]+Math.cos(a)*r,p[1]+Math.sin(a)*r,p[2]-rand()*5],[.04+Math.min(.07,k.reviews*.007),.09,.04],[0,a,.3]),rgb(k.kind==='flashcard'?'#dcc491':'#a7c7b5'),0);});}
  if(s.region==='journal'){const p=reg.journal,col=rgb('#ddc49b');draw(ring,transform([p[0],p[1],p[2]],[3.5,2.4,3],[.7,.3,-.3]),col,3,.18);const rand=seeded(s.data.seed+417);s.data.journal.slice(0,120).forEach(j=>{const a=rand()*6.28,r=.6+rand()*2.5;draw(crystal,transform([p[0]+Math.cos(a)*r,p[1]+Math.sin(a)*r*.75,p[2]-rand()*3],[.03,.08,.03],[0,0,.5]),rgb(j.unlockDate?'#afb6d2':'#e1c190'),3,.9);});}
  if(s.region==='observatory'){const p=reg.observatory,col=rgb('#a7c3ce');for(let i=0;i<4;i++)draw(ring,transform(p,[1.5+i*.55,1.5+i*.55,1.5+i*.55],[.15+i*.35,i*.4,0]),col,3,.18);const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d.toLocaleDateString('en-CA');});days.forEach((day,i)=>{const seconds=s.data.sessions.filter(x=>new Date(x.createdAt).toLocaleDateString('en-CA')===day).reduce((n,x)=>n+x.seconds,0);if(!seconds)return;const a=i/7*6.28,h=.1+Math.min(1.1,seconds/7200);draw(crystal,transform([p[0]+Math.cos(a)*2,p[1]+Math.sin(a)*2,p[2]],[.1,h,.1],[0,0,a-1.57]),col,0);});}
  if(s.region==='path'){const p=reg.path;Object.keys(reg).forEach((r,i)=>{const a=i/6*6.28,pos:V=[p[0]+Math.cos(a)*2,p[1]+Math.sin(a)*1.2,p[2]-i*.05];draw(land,transform(pos,[.5,.7,.5]),rgb(['#8dbfa4','#a2bed6','#d1c6a8','#d5bb8e','#9cbbcb','#a9bca4'][i]),2);draw(crystal,transform([pos[0],pos[1]+.3,pos[2]],[.18,.3,.18],[0,time*.1,0]),color,0);});}
  elapsed+=dt;frames++;if(elapsed>=4){if(frames/elapsed<23){bad++;if(bad===2&&mode==='Immersive'){mode='Balanced';ratio=1;resize();s.onQuality('Balanced · adaptado');}if(bad>=4&&frames/elapsed<15){onFallback();cleanup();return;}}else bad=0;elapsed=0;frames=0;}
 }
 const lost=(e:Event)=>{e.preventDefault();onFallback();cleanup();};canvas.addEventListener('webglcontextlost',lost);frame=requestAnimationFrame(render);
 function cleanup(){if(stopped)return;stopped=true;cancelAnimationFrame(frame);observer.disconnect();canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerdown',down);window.removeEventListener('pointerup',up);canvas.removeEventListener('webglcontextlost',lost);meshes.forEach(m=>{gl!.deleteBuffer(m.buffer);gl!.deleteBuffer(m.normal);});gl!.deleteProgram(program);gl!.deleteShader(vs);gl!.deleteShader(fs);canvas.remove();}
 return cleanup;
}
