'use client';
import {qualityName} from '@/lib/warma-copy';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Wind,Route,ScanLine,Feather,Sprout,Hand,Palette,ArrowUpRight,ArrowDown,AudioLines,BookOpen,Check,ChevronRight,Clock3,Compass,Download,Flame,Flag,Globe2,HelpCircle,Layers,Menu,Orbit,Plus,Settings2,Sparkles,Star,Target,Volume2,VolumeX,WifiOff,X} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter} from '@/components/ui/sidebar';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Progress} from '@/components/ui/progress';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {type Region,type Mood,type WorldState,useWorld,initWorld,mutateWorld,getWorld,uid,xp,level,levels,thresholds,streak,today,recommendation,finishSession,remainingSeconds,addMission} from '@/lib/itaca-store';
import {setSound,navigateSound,successSound} from '@/lib/itaca-audio';
import {observeOfflineReadiness} from '@/lib/offline-readiness';
import Core,{regions} from './core';
import WarmaHome from './warma-home';
import WarmaOnboarding from './warma-onboarding';
import {VaultGate} from './local-protection';
import {useProtection,lockWorld} from '@/lib/itaca-store';
import {shouldOfferOnboarding} from '@/lib/warma-onboarding';
import {Decompression,WarmaPath,Mirror,BodyPause,Support,PeaceReminders} from './warma-wellbeing';
import {Garden,RegulationObservatory,EmotionArt} from './warma-garden';
import {Focus,Missions} from './focus-missions';
import Projects from './projects';
import Journal from './journal';
import Memory from './memory';
import Games from './games';
import {Observatory,Path,Dreams} from './observatory';
import Settings from './settings';
import {Modal,Choices,Pick,Tip,act,notifyError,timeLabel} from './ui';
const nav=[{id:'world',label:'Mi espacio',icon:ScanLine},{id:'path',label:'Camino a WARMA',icon:Route},{id:'mirror',label:'Espejo',icon:ScanLine},{id:'journal',label:'Bitácora',icon:Feather},{id:'garden',label:'Mi jardín',icon:Sprout},{id:'focus',label:'Concentración',icon:Target},{id:'body',label:'Pausas y cuerpo',icon:Hand},{id:'art',label:'Atelier',icon:Palette},{id:'observatory',label:'Mi ritmo',icon:Globe2},{id:'projects',label:'Proyectos',icon:Orbit},{id:'memory',label:'Memoria',icon:BookOpen},{id:'missions',label:'Mis acciones',icon:Flag},{id:'games',label:'Microjuegos',icon:Layers},{id:'dreams',label:'Horizontes',icon:Sparkles},{id:'support',label:'Apoyo humano',icon:HelpCircle}];
const moods:{id:Mood;label:string}[]=[{id:'FOCUS',label:'Enfoque'},{id:'REFLECTION',label:'Reflexión'},{id:'CREATIVITY',label:'Crear'},{id:'REST',label:'Descanso'},{id:'PROGRESS',label:'Progreso'}];
export default function Itaca(){
 const {data,ready,error,saving}=useWorld();const [region,setRegion]=useState<Region>('world'),[hover,setHover]=useState<Region|null>(null),[qualityLabel,setQualityLabel]=useState('Adaptando…'),[checkin,setCheckin]=useState(false),[energy,setEnergy]=useState('media'),[load,setLoad]=useState('media'),[goal,setGoal]=useState('estudiar'),[why,setWhy]=useState(false),[menu,setMenu]=useState(false),[sound,setSoundState]=useState(false),[zen,setZen]=useState(false),[online,setOnline]=useState(true),[offlineReady,setOfflineReady]=useState(false),[installOpen,setInstallOpen]=useState(false),[installEvent,setInstallEvent]=useState<any>(null),[tick,setTick]=useState(0),[selectedProject,setSelectedProject]=useState<string|null>(null),[focusProject,setFocusProject]=useState('none'),[sysReduced,setSysReduced]=useState(false),[storyProgress,setStoryProgress]=useState(0),[travel,setTravel]=useState(false),[pause,setPause]=useState(false),[reminder,setReminder]=useState(''),[breakDue,setBreakDue]=useState(false);
 const [onboardingOpen,setOnboardingOpen]=useState(false);
 const [focusDuration,setFocusDuration]=useState<number|undefined>(undefined);
 const protection=useProtection();
 const onboardingOffered=useRef(false);
 const activeSeconds=useRef(0),finishing=useRef(false),travelTimer=useRef<ReturnType<typeof setTimeout>|null>(null),main=useRef<HTMLElement>(null),cursor=useRef<HTMLDivElement>(null);
 const reduced=data.prefs.reducedMotion||sysReduced,l=level(data),rec=recommendation(data),focused=region==='focus'&&!!data.timer,quiet=zen||focused;
 const navigate=useCallback((r:Region,minutes?:number)=>{setFocusDuration(r==='focus'?minutes:undefined);setRegion(r);setHover(null);setMenu(false);setZen(false);setStoryProgress(0);setTravel(true);if(travelTimer.current)clearTimeout(travelTimer.current);travelTimer.current=setTimeout(()=>setTravel(false),reduced?20:550);window.scrollTo({top:0,behavior:'instant'});navigateSound((regions.findIndex(x=>x.id===r)-2)/8);const hash=r==='world'?'':`#${r}`;if(location.hash!==hash)history.pushState({region:r},'',location.pathname+location.search+hash);setTimeout(()=>main.current?.focus({preventScroll:true}),50);},[reduced]);
 useEffect(()=>{void initWorld().catch(notifyError);const match=matchMedia('(prefers-reduced-motion: reduce)');setSysReduced(match.matches);const onMatch=()=>setSysReduced(match.matches);match.addEventListener('change',onMatch);setOnline(navigator.onLine);const onNetwork=()=>setOnline(navigator.onLine);window.addEventListener('online',onNetwork);window.addEventListener('offline',onNetwork);const onInstall=(e:Event)=>{e.preventDefault();setInstallEvent(e);};window.addEventListener('beforeinstallprompt',onInstall);const route=(event?:Event)=>{const hash=location.hash.slice(1);if(hash==='main-content')return;const next=hash===''?'world':hash;if([...nav.map(n=>n.id),'settings','story'].includes(next)){setRegion(next as Region);setZen(false);setMenu(false);setHover(null);setStoryProgress(0);if(event){window.scrollTo({top:0,behavior:'instant'});setTimeout(()=>main.current?.focus({preventScroll:true}),50);}}};route();window.addEventListener('popstate',route);window.addEventListener('hashchange',route);return ()=>{match.removeEventListener('change',onMatch);window.removeEventListener('online',onNetwork);window.removeEventListener('offline',onNetwork);window.removeEventListener('beforeinstallprompt',onInstall);window.removeEventListener('popstate',route);window.removeEventListener('hashchange',route);};},[]);
 useEffect(()=>{if(!ready||error||region!=='world'||onboardingOffered.current||!shouldOfferOnboarding(data))return;onboardingOffered.current=true;setOnboardingOpen(true);},[ready,error,region,data]);
 useEffect(()=>{if(protection.status!=='locked')return;void setSound(false).catch(()=>{});setSoundState(false);setPause(false);setOnboardingOpen(false);setMenu(false);setCheckin(false);setZen(false);},[protection.status]);
 useEffect(()=>{const onLeave=()=>{lockWorld();setSoundState(false);void setSound(false).catch(()=>{});};window.addEventListener('pagehide',onLeave);return ()=>{window.removeEventListener('pagehide',onLeave);void setSound(false).catch(()=>{});};},[]);
 useEffect(()=>{main.current?.scrollTo({top:0,left:0,behavior:'instant'});},[region]);
 useEffect(()=>{if(!data.timer)return;const interval=setInterval(()=>setTick(t=>t+1),500);return ()=>clearInterval(interval);},[!!data.timer]);
 useEffect(()=>{document.documentElement.style.fontSize=`${data.prefs.textScale*100}%`;return ()=>{document.documentElement.style.fontSize='';};},[data.prefs.textScale]);
 useEffect(()=>{if(!ready){setOfflineReady(false);return;}return observeOfflineReadiness(setOfflineReady);},[ready]);
 useEffect(()=>{if(!data.timer?.endsAt||remainingSeconds(data.timer)>0||finishing.current)return;finishing.current=true;finishSession(data.timer.id).then(()=>{successSound();toast.success('Sesión guardada. Ahora puedes hacer una pausa.');}).catch(notifyError).finally(()=>{finishing.current=false;});},[tick,data.timer]);
 useEffect(()=>{if(region!=='story')return;const update=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setStoryProgress(max>0?window.scrollY/max:0);};window.addEventListener('scroll',update,{passive:true});update();return ()=>window.removeEventListener('scroll',update);},[region]);
 useEffect(()=>{if(reduced||!matchMedia('(pointer:fine)').matches)return;const onMove=(e:PointerEvent)=>{if(!cursor.current)return;cursor.current.style.transform=`translate(${e.clientX+17}px, ${e.clientY+18}px)`;const node=e.target as HTMLElement,portal=node.closest('[data-portal]'),can=node.closest('.world-canvas');const drag=node.closest('.graph-surface'),focus=node.closest('.hero-cta,.focus-setup .primary'),open=node.closest('.memory-node,.memory-room,.planet-hotspot');cursor.current.textContent=portal?'ENTRAR':drag?'ARRASTRAR':focus?'ENFOQUE':open?'ABRIR':can?'EXPLORAR':'';cursor.current.style.opacity=portal||can||drag||focus||open?'1':'0';};window.addEventListener('pointermove',onMove);return ()=>window.removeEventListener('pointermove',onMove);},[reduced]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:any)=>Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});
 register({name:'warma_read_space',title:'Leer mi mundo',description:'Read local progress, counts and current region without journal content.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>{const d=getWorld();return {pauses:d.wellbeing.pauses.length,missions:d.missions.length,projects:d.projects.length,sessions:d.sessions.length};}});
 register({name:'warma_navigate_region',title:'Explorar una región',description:'Open an existing region. Does not complete any activity.',inputSchema:{type:'object',properties:{region:{type:'string',enum:nav.map(n=>n.id)}},required:['region'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!input||!nav.some(n=>n.id===input.region))throw new Error('Unknown region');navigate(input.region);await new Promise(r=>setTimeout(r,0));return {region:input.region};}});
 register({name:'warma_create_mission',title:'Crear una misión',description:'Create and save a local mission using the same action as the mission form.',inputSchema:{type:'object',properties:{title:{type:'string',minLength:1,maxLength:180},minutes:{type:'integer',minimum:1,maximum:480}},required:['title','minutes'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>{if(!input||typeof input.title!=='string'||!input.title.trim()||input.title.length>180||!Number.isInteger(input.minutes)||input.minutes<1||input.minutes>480)throw new Error('Invalid mission');await addMission(input.title,'side',input.minutes);navigate('missions');return {created:true,title:input.title};}});return ()=>lifecycle.abort();},[navigate]);
 const openPause=useCallback(async()=>{const d=getWorld();if(d.timer?.endsAt){const ok=await act(()=>mutateWorld(v=>{if(v.timer?.endsAt){v.timer.remaining=remainingSeconds(v.timer);v.timer.endsAt=null;}}));if(!ok)return;}try{await setSound(false);}catch{}setSoundState(false);setPause(true);setReminder('');setBreakDue(false);activeSeconds.current=0;},[]);
 useEffect(()=>{if(!ready)return;const t=setInterval(()=>{if(document.hidden||pause||zen)return;activeSeconds.current+=30;if(activeSeconds.current>=45*60){setBreakDue(true);activeSeconds.current=0;}const r=getWorld().wellbeing.reminders;if(!r.enabled||focused||Date.now()-r.lastAt<r.interval*60000)return;const choices=[r.water?'¿Un momento para tomar agua?':'',r.stretch?'¿Te vendría bien cambiar de postura?':'',r.journal?'¿Quieres guardar una idea de tu día?':''].filter(Boolean);if(!choices.length)return;setReminder(choices[Math.floor(Date.now()/60000)%choices.length]);void mutateWorld(d=>{d.wellbeing.reminders.lastAt=Date.now();}).catch(notifyError);},30000);return ()=>clearInterval(t);},[ready,pause,zen,focused]);
 async function toggleAudio(){try{const enabled=await setSound(!sound);setSoundState(enabled);}catch(e){notifyError(e);}}
 async function install(){if(installEvent){await installEvent.prompt();const result=await installEvent.userChoice;if(result.outcome==='accepted')toast.success('Instalación solicitada al navegador');setInstallEvent(null);}else setInstallOpen(true);}
 async function saveCheckin(){if(await act(()=>mutateWorld(d=>{d.checkin={date:today(),energy:energy as any,load:load as any,goal:goal as any};d.wellbeing.checkins.push({id:uid(),energy:energy as any,load:load as any,createdAt:new Date().toISOString()});d.mood=goal==='descansar'?'REST':goal==='reflexionar'?'REFLECTION':goal==='crear'?'CREATIVITY':goal==='estudiar'?'FOCUS':'PROGRESS';}),'Tu espacio se ha ajustado para hoy'))setCheckin(false);}
 const effectiveMood=region==='focus'?'FOCUS':region==='journal'?'REFLECTION':region==='story'?(['PROGRESS','REFLECTION','FOCUS','CREATIVITY','PROGRESS','REST','PROGRESS'] as Mood[])[Math.min(6,Math.floor(storyProgress*7))]:data.mood;
 if(protection.status==='locked')return <><VaultGate error={error}/><Toaster position="bottom-right" theme="dark" toastOptions={{className:'itaca-toast'}}/></>;
 return <SidebarProvider className={'itaca warma '+(quiet?'zen ':'')+(reduced?'reduced ':'')+`region-${region} mood-${effectiveMood.toLowerCase()}`} style={{'--sidebar-width':'78px','--sidebar-width-icon':'78px'} as React.CSSProperties}><a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();main.current?.focus({preventScroll:true});}}>Saltar al contenido</a><div ref={cursor} className="context-cursor" aria-hidden="true"/>
 <nav className="primary-navigation" aria-label="Navegación principal"><Sidebar collapsible="none" className="nav-rail"><button className="brand-symbol" aria-label="WARMA · mi espacio" onClick={()=>navigate('world')}><Wind size={29} strokeWidth={1.3}/></button><SidebarContent><SidebarMenu>{nav.slice(0,9).map((n,i)=><SidebarMenuItem key={n.id}><Tip label={n.label}><SidebarMenuButton className="rail-button" aria-label={n.label} isActive={region===n.id} aria-current={region===n.id?'page':undefined} onClick={()=>navigate(n.id as Region)}><n.icon size={21} strokeWidth={1.45}/></SidebarMenuButton></Tip>{i===4&&<div className="rail-divider"/>}</SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><Tip label="Todas las herramientas"><button className="rail-button" aria-label="Todas las herramientas" aria-expanded={menu} aria-haspopup="dialog" onClick={()=>setMenu(true)}><Menu size={20}/></button></Tip><Tip label="Preferencias y tus datos"><button className={'rail-button '+(region==='settings'?'selected':'')} aria-label="Preferencias y tus datos" aria-current={region==='settings'?'page':undefined} onClick={()=>navigate('settings')}><Settings2 size={20} strokeWidth={1.5}/></button></Tip><span className="rail-edition">W / 2026</span></SidebarFooter></Sidebar></nav>
 <div className="app-body"><header className="topbar"><button className="wordmark" onClick={()=>navigate('world')}>WARMA<span>A TU RITMO</span></button><div className="top-breadcrumb">TU ESPACIO PERSONAL<span>/</span><b>{region==='world'?'VOLVER AL CENTRO':nav.find(n=>n.id===region)?.label.toUpperCase()||'TU ESPACIO'}</b></div><div className="top-actions"><button className="pause-top" onClick={openPause}><Wind size={17}/>Necesito parar</button><button className="quality-pill" onClick={()=>navigate('settings')}><span className="quality-dot"/>{qualityName(qualityLabel).split(' · ')[0]}</button><button className="icon-button" onClick={toggleAudio} aria-label={sound?'Silenciar todo':'Activar sonido ambiental'}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button className="profile-button" aria-label="Mi perfil" onClick={()=>navigate('settings')}><span>{data.name?data.name[0].toUpperCase():'M'}</span></button></div></header>
 <Core data={data} region={region} hover={hover} mood={effectiveMood} quality={data.prefs.quality} reduced={reduced||pause||onboardingOpen} focusProgress={data.timer?1-remainingSeconds(data.timer)/data.timer.total:0} storyProgress={region==='story'?storyProgress:0} onRegion={navigate} onProject={id=>setSelectedProject(id)} onQuality={setQualityLabel}/>
 {!online&&<div className="offline-banner"><WifiOff size={15}/>Sin conexión · tus datos siguen en este dispositivo.</div>}{error&&<div className="storage-error" role="alert">{error}<button onClick={()=>void initWorld().catch(notifyError)}>Reintentar</button></div>}
 <main id="main-content" className={'main-content '+(travel?'travelling':'')} tabIndex={-1} ref={main}>
 {region==='world'&&<WarmaHome data={data} navigate={navigate} onOnboarding={()=>setOnboardingOpen(true)} onPause={openPause} onHover={setHover} onCheckin={()=>{if(data.checkin){setEnergy(data.checkin.energy);setLoad(data.checkin.load);setGoal(data.checkin.goal);}setCheckin(true);}} saving={saving} ready={ready}/>}
 {ready&&region==='mirror'&&<Mirror data={data} navigate={navigate}/>}
 {ready&&region==='body'&&<BodyPause data={data} onPause={openPause}/>}
 {ready&&region==='garden'&&<Garden data={data} navigate={navigate}/>}
 {ready&&region==='art'&&<EmotionArt data={data}/>}
 {region==='support'&&<Support/>}
 {region==='focus'&&<Focus data={data} initialMinutes={focusDuration} initialProject={focusProject} tick={tick} onExit={()=>navigate('world')}/>}{region==='missions'&&<Missions data={data}/>}{region==='projects'&&<Projects data={data} selected={selectedProject} onSelect={setSelectedProject} onFocus={id=>{setFocusProject(id);navigate('focus');}}/>}{ready&&region==='journal'&&<Journal data={data} zen={zen} onZen={setZen}/>}{region==='memory'&&<Memory data={data} onProject={id=>{setSelectedProject(id);navigate('projects');}}/>}{region==='games'&&<Games data={data}/>}{region==='observatory'&&<RegulationObservatory data={data}/>}{region==='path'&&<WarmaPath data={data} navigate={navigate} onPause={openPause}/>}{region==='dreams'&&<Dreams data={data}/>}{region==='settings'&&<Settings data={data} sound={sound} onSound={toggleAudio} onInstall={install} qualityLabel={qualityLabel} offlineReady={offlineReady} onOnboarding={()=>setOnboardingOpen(true)}/>}{region==='story'&&<Story navigate={navigate}/>}
 </main>{(reminder||breakDue)&&!quiet&&!pause&&<div className="peace-banner" role="status"><Wind size={19}/><span>{breakDue?'Llevas un rato aquí. ¿Hacemos una pausa?':reminder}</span><button className="text-link" onClick={openPause}>Hacer una pausa</button><button className="icon-button" aria-label="Omitir recordatorio" onClick={()=>{setReminder('');setBreakDue(false);}}><X size={17}/></button></div>}<div className="persistent-controls"><button className="pause-floating" aria-label="Necesito parar" onClick={openPause}><Wind size={20}/><span>Necesito parar</span></button>{data.timer&&region!=='focus'&&<button className="floating-timer" aria-label={`Volver al enfoque · ${timeLabel(remainingSeconds(data.timer))}`} onClick={()=>navigate('focus')}><Target size={17}/>{timeLabel(remainingSeconds(data.timer))}<span>Volver al enfoque</span></button>}</div>
 <nav className="mobile-nav" aria-label="Navegación móvil">{nav.slice(0,4).map(n=><button className={region===n.id?'active':''} key={n.id} aria-current={region===n.id?'page':undefined} onClick={()=>navigate(n.id as Region)}><n.icon size={20}/><span>{n.id==='world'?'Inicio':n.id==='path'?'Camino':n.label}</span></button>)}<button aria-label="Explorar todas las herramientas" aria-expanded={menu} aria-haspopup="dialog" onClick={()=>setMenu(true)}><Menu size={20}/><span>Explorar</span></button></nav></div>
 <WarmaOnboarding reduced={reduced} open={onboardingOpen} onOpen={setOnboardingOpen} data={data} navigate={navigate}/><Decompression open={pause} onOpen={setPause} data={data} reduced={reduced}/><Modal open={checkin} onOpen={setCheckin} title="¿Cómo llegas hoy?" description="Tu espacio se adapta a ti. Puedes cambiarlo cuando quieras."><div className="form-stack"><div className="field-label">Mi energía<Choices value={energy} onChange={setEnergy} options={['baja','media','alta']} label="Energía"/></div><div className="field-label">Mi carga de hoy<Choices value={load} onChange={setLoad} options={['ligera','media','alta']} label="Carga"/></div><label className="field-label">Hoy quiero<Pick value={goal} onChange={setGoal} label="Objetivo de hoy" options={['estudiar','organizarme','reflexionar','descansar','crear'].map(s=>({value:s,label:s}))}/></label><button className="btn primary" onClick={saveCheckin}>Entrar a mi día <ArrowUpRight size={17}/></button></div></Modal><Modal open={why} onOpen={setWhy} title="¿Por qué veo esto?" description="Una sugerencia transparente."><p>{rec.reason}</p><p className="muted small">Usamos tu registro del día, la hora de tu dispositivo y las fechas de tus proyectos. No hacemos diagnósticos. Tú eliges el siguiente paso.</p></Modal><Modal open={menu} onOpen={setMenu} title="Tu espacio WARMA" description="Autorregulación y herramientas académicas."><nav className="mobile-menu-grid" aria-label="Todas las herramientas">{[...nav,{id:'settings',label:'Preferencias y datos',icon:Settings2}].map(n=><button key={n.id} aria-current={region===n.id?'page':undefined} onClick={()=>navigate(n.id as Region)}><n.icon size={21}/>{n.label}<ArrowUpRight size={15}/></button>)}</nav></Modal><Modal open={installOpen} onOpen={setInstallOpen} title="Lleva WARMA contigo" description="Instala tu universo desde el menú del navegador."><p>En Chrome o Edge, busca «Instalar aplicación» en el menú. En iPhone o iPad, abre el enlace en Safari, pulsa Compartir y elige «Añadir a pantalla de inicio».</p><p className="muted">La primera apertura necesita conexión. Después de preparar sus recursos, podrás usar tus herramientas y datos sin conexión en este dispositivo.</p></Modal><Toaster position="bottom-right" theme="dark" toastOptions={{className:'itaca-toast'}}/>
 </SidebarProvider>;
}
function SunIcon(){return <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.4 1.4m11.2 11.2L19 19M5 19l1.4-1.4M17.6 6.4 19 5"/></svg>;}
function Story({navigate}:{navigate:(r:Region)=>void}){const scenes=[['01 / EL ORIGEN','Un espacio.\nA tu ritmo.','Organiza, pausa, reflexiona y continúa.'],['02 / TU REALIDAD','Cada estudiante\nparte de un lugar distinto.','Por eso este camino empieza contigo, no con una comparación.'],['03 / EQUIDAD DIGITAL','La misma oportunidad.\nDistinta intensidad.','Esencial, Equilibrada e Inmersiva. Tus herramientas y tu progreso, en los tres.'],['04 / EL CAMINO','No necesitas verlo todo.\nSólo el siguiente paso.','Concentrarte, organizar, recordar, reflexionar. Elige una dirección.'],['05 / TU MUNDO','Lo que haces\ndeja una huella.','Tu jardín crece con las acciones y las pausas. Nunca pierde progreso por descansar.'],['06 / TUS DATOS','Un espacio personal.\nTambién sin conexión.','Tus palabras y tus ideas permanecen en tu dispositivo. Puedes exportarlas cuando quieras.'],['07 / WARMA','El viaje no se mide\ncon el camino de otros.','Comienza el tuyo.']];return <div className="story">{scenes.map((s,i)=><section className="story-scene" key={s[0]}><div><span className="eyebrow">{s[0]}</span><h1>{s[1]}</h1><p>{s[2]}</p>{i===6?<button className="btn primary" onClick={()=>navigate('world')}>Comenzar mi viaje <ArrowUpRight size={17}/></button>:<span className="story-scroll"><ArrowDown size={16}/>Sigue explorando</span>}</div></section>)}</div>;}
