'use client';
import {counted} from '@/lib/warma-copy';
import {useMemo,useState} from 'react';
import {ArrowUpRight,Eye,RotateCcw,Star,Link2} from 'lucide-react';
import {type WorldState,type Knowledge,today,seeded} from '@/lib/itaca-store';
import {formatDate} from './ui';
const point=(a:number,r:number,cx=270,cy=250)=>({x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r});
function arc(a:number,b:number,r:number){const p=point(a,r),q=point(b,r);return `M${p.x},${p.y} A${r},${r} 0 ${b-a>Math.PI?1:0} 1 ${q.x},${q.y}`;}
export function RhythmInstrument({data}:{data:WorldState}){
 const [selected,setSelected]=useState<number|null>(null),days=Array.from({length:7},(_,i)=>{const dt=new Date();dt.setDate(dt.getDate()-6+i);const sessions=data.sessions.filter(s=>new Date(s.createdAt).toDateString()===dt.toDateString());return {label:dt.toLocaleDateString('es-PE',{weekday:'short'}),date:dt.toISOString(),minutes:Math.floor(sessions.reduce((n,s)=>n+s.seconds,0)/60),count:sessions.length};}),max=Math.max(15,...days.map(d=>d.minutes)),total=days.reduce((n,d)=>n+d.minutes,0);
 return <div className="rhythm-instrument"><div className="instrument-plot"><svg viewBox="0 0 540 510" role="img" aria-label={`Enfoque en los últimos siete días: ${days.map(d=>d.label+' '+counted(d.minutes,'minuto','minutos')).join(', ')}`}><defs><radialGradient id="instrument-light"><stop stopColor="#718f8940"/><stop offset="1" stopColor="#718f8900"/></radialGradient></defs><circle cx="270" cy="250" r="235" fill="url(#instrument-light)"/>{[85,125,165,203].map(r=><circle key={r} cx="270" cy="250" r={r} fill="none" stroke="#a5bcb922" strokeDasharray={r===125?'2 7':undefined}/>)}{Array.from({length:84},(_,i)=>{const a=i/84*Math.PI*2,p=point(a,211),q=point(a,i%7===0?225:216);return <line key={i} x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke={i%7===0?'#abc3bd6f':'#abc3bd22'}/>;})}{days.map((d,i)=>{const a=i/7*Math.PI*2-Math.PI/2+.07,b=a+Math.PI*2/7-.14,p=point((a+b)/2,239),r=125+d.minutes/max*68;return <g key={i} className="instrument-day" role="button" tabIndex={0} aria-label={`${d.label}: ${counted(d.minutes,'minuto','minutos')}, ${counted(d.count,'sesión','sesiones')}`} onFocus={()=>setSelected(i)} onMouseEnter={()=>setSelected(i)} onMouseLeave={()=>setSelected(null)} onClick={()=>setSelected(selected===i?null:i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')setSelected(i);}}><path d={arc(a,b,165)} fill="none" stroke="#a7c1bb0b" strokeWidth="58"/><path d={arc(a,b,r)} fill="none" stroke={d.minutes?'#adcbb8':'#688b813f'} strokeWidth={d.minutes?8:1} strokeLinecap="round"/><text x={p.x} y={p.y+4} textAnchor="middle" fill={selected===i?'#e2efd8':'#96b3aa'}>{d.label.replace('.','').toUpperCase()}</text></g>;})}<circle cx="270" cy="250" r="72" fill="#0a151acc" stroke="#b1c8bf30"/><text className="instrument-value" x="270" y="253" textAnchor="middle" fill="#d8e8d2">{selected===null?total:days[selected].minutes}</text><text className="instrument-unit" x="270" y="280" textAnchor="middle" fill="#92aca1">MINUTOS</text><path d="M270 8v16 M270 476v18 M20 250h15 M505 250h16" stroke="#a4b9b053"/></svg><span className="instrument-caption">{selected===null?'TU ÓRBITA · ÚLTIMOS 7 DÍAS':`${formatDate(days[selected].date)} · ${counted(days[selected].count,'sesión','sesiones')}`}</span></div><div className="rhythm-story"><span className="eyebrow">EL RITMO DE TU SEMANA</span><h2>Tu tiempo<br/>tiene su<br/><em>propia órbita.</em></h2><p>{total?`Has dedicado ${counted(total,'minuto','minutos')} a concentrarte esta semana. Cada arco refleja el tiempo real de un día.`:'Tu órbita está abierta. Cada sesión dibujará un arco; su radio reflejará los minutos de ese día.'}</p><div className="rhythm-key"><span/><p>Radio · minutos de enfoque<br/>Un sector · un día</p></div><p className="small muted">Selecciona un día para explorar su actividad.</p></div></div>;
}
export function MemoryAtlas({items,title,onSelect}:{items:Knowledge[];title:string;onSelect:(id:string)=>void}){
 const [hover,setHover]=useState<string|null>(null);const shown=items.slice(0,36);const positions=shown.map((k,i)=>{const ring=Math.floor(i/9),a=(i%9)/Math.min(9,shown.length)*Math.PI*2-.6+ring*.22;return {id:k.id,x:50+Math.cos(a)*(25+ring*7),y:50+Math.sin(a)*(29+ring*3)};});
 return <div className="memory-atlas"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{[22,34,43].map(r=><ellipse key={r} cx="50" cy="50" rx={r} ry={r*.9} fill="none" stroke="#bcba972b" strokeWidth=".1" strokeDasharray={r===34?'.2 1':undefined}/>)}{shown.flatMap(k=>k.links.map(id=>{const a=positions.find(p=>p.id===k.id),b=positions.find(p=>p.id===id);return a&&b?<line key={k.id+id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={hover===k.id||hover===id?'#e4d8b9':'#bdc2a33b'} strokeWidth={hover===k.id?.25:.12}/>:null;}))}</svg><div className="atlas-center"><span className="eyebrow">PALACIO DE LA MEMORIA</span><h2>{title}</h2><p>{counted(items.length,'aprendizaje','aprendizajes')}</p></div>{shown.map((k,i)=><button key={k.id} className={'memory-node '+(k.kind==='flashcard'&&k.due<=today()?'due':'')+(hover&&hover!==k.id&&!shown.find(x=>x.id===hover)?.links.includes(k.id)?' dimmed':'')} style={{left:positions[i].x+'%',top:positions[i].y+'%','--memory-intensity':Math.min(1,.25+k.reviews*.12)} as React.CSSProperties} onPointerEnter={()=>setHover(k.id)} onPointerLeave={()=>setHover(null)} onFocus={()=>setHover(k.id)} onBlur={()=>setHover(null)} onClick={()=>onSelect(k.id)} aria-label={`${k.title}, ${counted(k.reviews,'repaso','repasos')}${k.kind==='flashcard'&&k.due<=today()?', pendiente de repaso':''}`}><span className="memory-node-symbol">{k.kind==='flashcard'?<RotateCcw size={17}/>:k.kind==='formula'?<span>ƒ</span>:<Star size={17}/>}</span><strong>{k.title}</strong><small>{k.kind==='flashcard'?(k.due<=today()?'Para repasar hoy':`Vuelve el ${formatDate(k.due)}`):`${counted(k.links.length,'conexión','conexiones')}`}</small></button>)}<div className="atlas-key"><span className="memory-key-dot"/>Repaso pendiente <span className="memory-key-ring"/>Intensidad · veces repasado</div>{items.length>36&&<span className="atlas-overflow">36 visibles · todos los aprendizajes están en el índice</span>}</div>;
}
export function JourneyTrail({data}:{data:WorldState}){
 const [selected,setSelected]=useState<string|null>(null),events=data.events.slice(-50),active=events.find(e=>e.id===selected),positions=events.map((e,i)=>{const t=events.length===1?.08:i/Math.max(1,events.length-1);return {x:50+t*900,y:105+Math.sin(t*Math.PI*3)*55};});
 return <div className="journey-trail"><div className="row-between"><span className="eyebrow">LAS HUELLAS DE TU CAMINO</span><span className="small muted">{counted(data.events.length,'paso registrado','pasos registrados')}</span></div><svg viewBox="0 0 1000 220" role="img" aria-label={`Camino de ${counted(data.events.length,'hito real','hitos reales')}`}><path d="M50 105C150 200 260 200 350 105S550 10 650 105 850 200 950 105" fill="none" stroke="#a9bc9738" strokeDasharray={events.length?'':'3 6'}/>{positions.map((p,i)=><g key={events[i].id} role="button" tabIndex={0} aria-label={`${events[i].title}, ${formatDate(events[i].createdAt)}`} onMouseEnter={()=>setSelected(events[i].id)} onFocus={()=>setSelected(events[i].id)} onClick={()=>setSelected(events[i].id)} onKeyDown={e=>{if(e.key==='Enter')setSelected(events[i].id);}}><circle cx={p.x} cy={p.y} r={events[i].type==='project_completed'?10:5} fill={events[i].type==='journal_entry_created'?'#d8c195':'#c5d6b3'}/><circle cx={p.x} cy={p.y} r="16" fill="transparent" stroke={selected===events[i].id?'#dce8c0':'transparent'}/></g>)}<text x="50" y="205" fill="#9ab18a" fontSize="13">EL COMIENZO</text><text x="950" y="205" textAnchor="end" fill="#9ab18a" fontSize="13">TU SIGUIENTE PASO</text></svg><div className="trail-caption" aria-live="polite">{active?<><span>{formatDate(active.createdAt)}</span><b>{active.title}</b><span>+{active.xp} XP</span></>:<p>{events.length?'Explora una huella para recordar ese momento.':'El camino se dibuja con tus acciones. La primera huella será tuya.'}</p>}</div></div>;
}
