'use client';
import {counted} from '@/lib/warma-copy';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Plus,Search,Maximize2,Minimize2,LockKeyhole,Star,Trash2,Check,Clock3} from 'lucide-react';
import {type WorldState,uid,mutateWorld,reward,today} from '@/lib/itaca-store';
import {ViewHeading,Modal,Empty,act,formatDate,Confirm} from './ui';
export default function Journal({data,zen,onZen}:{data:WorldState;zen:boolean;onZen:(v:boolean)=>void}){
 const [title,setTitle]=useState(data.journalDraft.title),[body,setBody]=useState(data.journalDraft.body),[tags,setTags]=useState(data.journalDraft.tags),[search,setSearch]=useState(''),[selected,setSelected]=useState<string|null>(null),[capsule,setCapsule]=useState(false),[unlock,setUnlock]=useState(''),[remove,setRemove]=useState(false),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false);
 const draft=useRef({title,body,tags,dirty});draft.current={title,body,tags,dirty};const skip=useRef(false);
 useEffect(()=>{if(!dirty||selected)return;const timer=setTimeout(()=>{if(!skip.current)act(()=>mutateWorld(d=>{d.journalDraft={title,body,tags};}));},900);return ()=>clearTimeout(timer);},[title,body,tags,dirty,selected]);
 useEffect(()=>()=>{const q=draft.current;if(q.dirty&&!skip.current)void act(()=>mutateWorld(d=>{d.journalDraft={title:q.title,body:q.body,tags:q.tags};}));},[]);
 const entry=data.journal.find(j=>j.id===selected),locked=!!(entry?.unlockDate&&entry.unlockDate>today());
 function choose(id:string|null){if(!selected&&dirty)act(()=>mutateWorld(d=>{d.journalDraft={title,body,tags};}));setSelected(id);setDirty(false);if(!id){setTitle(data.journalDraft.title);setBody(data.journalDraft.body);setTags(data.journalDraft.tags);}}
 async function save(){if(!body.trim()||saving)return;setSaving(true);skip.current=true;setDirty(false);const id=uid();if(await act(()=>mutateWorld(d=>{d.journal.push({id,title:title.trim()||'Una nueva reflexión',body:body.trim(),tags:tags.split(',').map(t=>t.trim()).filter(Boolean).slice(0,30),createdAt:new Date().toISOString(),...(capsule&&unlock?{unlockDate:unlock}:{})});d.journalDraft={title:'',body:'',tags:''};}),'Reflexión guardada en tu dispositivo')){skip.current=true;setDirty(false);setTitle('');setBody('');setTags('');setCapsule(false);setSelected(id);}else{skip.current=false;setDirty(true);}setSaving(false);}
 const history=data.journal.filter(j=>(j.unlockDate&&j.unlockDate>today()?j.title:[j.title,j.body,...j.tags].join(' ')).toLowerCase().includes(search.toLowerCase())).slice().reverse();
 return <section className={'workspace journal-view '+(zen?'journal-zen':'')}>
 {!zen&&<ViewHeading eyebrow="03 / BITÁCORA" title="Un espacio para escucharte." description="Tus palabras tienen espacio aquí. Escribe sólo lo que quieras conservar."/>}<div className="journal-layout">{!zen&&<aside className="journal-index"><button className="btn secondary" onClick={()=>choose(null)}><Plus size={16}/>Nueva reflexión</button><label className="search-field"><Search size={16}/><input aria-label="Buscar reflexiones" placeholder="Buscar mis palabras" value={search} onChange={e=>setSearch(e.target.value)}/></label>{history.length?history.map(j=><button className={'journal-entry-link '+(selected===j.id?'active':'')} key={j.id} onClick={()=>choose(j.id)}><span>{j.unlockDate?<LockKeyhole size={15}/>:<Star size={15}/>} {formatDate(j.createdAt)}</span><h3>{j.title}</h3><small>{j.unlockDate&&j.unlockDate>today()?`Se abre el ${formatDate(j.unlockDate)}`:j.tags.join(' · ')||'Reflexión personal'}</small></button>):<p className="muted small">{search?'No hay reflexiones que coincidan.':'Aquí podrás volver a tus palabras.'}</p>}</aside>}
 <article className="writing-space"><div className="writing-toolbar"><span className="eyebrow">{entry?formatDate(entry.createdAt):new Date().toLocaleDateString('es-PE',{weekday:'long',day:'numeric',month:'long'})}</span><button className="icon-button" aria-label={zen?'Salir de modo Zen':'Activar modo Zen'} onClick={()=>onZen(!zen)}>{zen?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button></div>
 {entry?(locked?<div className="capsule-locked"><LockKeyhole size={32}/><h2>{entry.title}</h2><p>Un mensaje de tu pasado, reservado para el {new Date(entry.unlockDate!+'T12:00:00').toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric'})}.</p><span className="small muted">La fecha es un recordatorio personal, no un bloqueo cifrado.</span></div>:<><h2 className="journal-title">{entry.title}</h2><div className="journal-body">{entry.body}</div><div className="tags">{entry.tags.map(t=><span key={t}>#{t}</span>)}</div><button className="text-link danger-text" onClick={()=>setRemove(true)}><Trash2 size={15}/>Eliminar reflexión</button></>):<><input className="journal-title-input" aria-label="Título de la reflexión" placeholder="Hoy quiero entender…" value={title} maxLength={180} onChange={e=>{setTitle(e.target.value);setDirty(true);skip.current=false;}}/><textarea className="journal-editor" aria-label="Escribe tu reflexión" placeholder={'¿Qué intentaste? ¿Qué funcionó? ¿Qué podrías ajustar?\n\nEmpieza donde estés.'} value={body} maxLength={40000} onChange={e=>{setBody(e.target.value);setDirty(true);skip.current=false;}}/><details className="journal-options"><summary>Más opciones</summary><label className="field-label compact-label">Etiquetas<input placeholder="aprendizaje, ideas, gratitud" value={tags} onChange={e=>{setTags(e.target.value);setDirty(true);}}/></label><button className="text-link" aria-pressed={capsule} onClick={()=>setCapsule(!capsule)}><Clock3 size={16}/>Cápsula del tiempo</button>{capsule&&<label className="field-label">Abrir a partir del<input type="date" min={today()} value={unlock} onChange={e=>setUnlock(e.target.value)}/><span className="small muted">La cápsula aparecerá al abrir WARMA desde esa fecha.</span></label>}</details><div className="writing-bottom"><span className="muted small">{counted(body.trim()?body.trim().split(/\s+/).length:0,'palabra','palabras')} · borrador local</span><button className="btn primary" onClick={save} disabled={saving||!body.trim()||(capsule&&!unlock)}>{saving?'Guardando…':'Guardar mi reflexión'}<ArrowUpRight size={16}/></button></div></>}
 </article></div><Confirm open={remove} onOpen={setRemove} title="¿Eliminar esta reflexión?" description="Desaparecerá de tu diario y de las estrellas de tu mundo. Puedes exportar un respaldo antes." onConfirm={()=>{if(entry)act(()=>mutateWorld(d=>{d.journal=d.journal.filter(j=>j.id!==entry.id);}),'Reflexión eliminada').then(ok=>{if(ok)setSelected(null);});}}/>
 </section>;
}
