'use client';
import {FEATURE_FLAGS} from '@/lib/feature-flags';
import {qualityName} from '@/lib/warma-copy';
import {PeaceReminders} from './warma-wellbeing';
import {useState} from 'react';
import {Download,Upload,Trash2,ShieldCheck,HardDrive} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {type WorldState,type Quality,mutateWorld,downloadJSON,resetWorld,useProtection} from '@/lib/itaca-store';
import {ViewHeading,Pick,Confirm,act} from './ui';
import {LocalProtectionControls,RestoreBackupDialog} from './local-protection';
export default function Settings({data,sound,onSound,onInstall,qualityLabel,offlineReady,onOnboarding}:{data:WorldState;sound:boolean;onSound:()=>void;onInstall:()=>void;qualityLabel:string;offlineReady:boolean;onOnboarding:()=>void}){
 const [name,setName]=useState(data.name),[remove,setRemove]=useState(false),[restore,setRestore]=useState<globalThis.File|null>(null);
 const protection=useProtection();
 const pref=(p:Partial<WorldState['prefs']>)=>act(()=>mutateWorld(d=>{Object.assign(d.prefs,p);}));
 return <section className="workspace settings-view">
 <ViewHeading eyebrow="TU ESPACIO / PREFERENCIAS" title="WARMA, a tu manera." description="Decide cómo habitar este espacio. Tus preferencias y tus datos siguen bajo tu control."/>
 <div className="settings-columns">
 <div>
 <section className="setting-section"><span className="setting-number">01 / TU ESPACIO</span><h2>Lo que quieres llamar tuyo.</h2><form className="inline-form" onSubmit={e=>{e.preventDefault();act(()=>mutateWorld(d=>{d.name=name.trim();}),'Nombre guardado');}}><input aria-label="Tu nombre" value={name} onChange={e=>setName(e.target.value)} placeholder="¿Cómo te llamas?" maxLength={80}/><button className="btn secondary">Guardar</button></form><p className="small muted">Tu nombre es opcional. Tu mundo tiene una semilla que se conserva en cada respaldo.</p><code className="seed-display">WARMA / {data.seed.toString(16).toUpperCase().padStart(8,'0')}</code><div className="setting-subgroup"><h3>Tu punto de partida</h3><p>Revisa cómo quieres empezar. Puedes omitir el autochequeo sin perder herramientas.</p>{!FEATURE_FLAGS.PSS10_ENABLED&&<p className="small muted">El autochequeo PSS-10 está en preparación. Puedes ajustar tus preferencias sin responderlo.</p>}<button className="text-link" onClick={onOnboarding}>Revisar mi punto de partida</button></div></section>
 <section className="setting-section"><span className="setting-number">02 / EXPERIENCIA</span><h2>A tu ritmo.</h2><label className="field-label">Calidad<Pick value={data.prefs.quality} onChange={v=>pref({quality:v as Quality})} label="Calidad visual" options={[{value:'auto',label:'Automática · se adapta a tu dispositivo'},{value:'immersive',label:'Inmersiva · mundo 3D completo'},{value:'balanced',label:'Equilibrada · 3D ligero'},{value:'essential',label:'Esencial · mínimo consumo'}]}/></label><p className="small muted">En uso: {qualityName(qualityLabel)}. Tus herramientas y datos permanecen disponibles en todos los modos.</p><label className="switch-row"><span>Ambiente sonoro<small>Se activa sólo cuando tú lo eliges.</small></span><Switch checked={sound} onCheckedChange={onSound}/></label></section>
 <section className="setting-section"><span className="setting-number">03 / ACCESIBILIDAD</span><h2>Hazlo cómodo para ti.</h2><label className="switch-row"><span>Movimiento reducido<small>Transiciones breves y entorno quieto.</small></span><Switch checked={data.prefs.reducedMotion} onCheckedChange={v=>pref({reducedMotion:v})}/></label><label className="field-label">Tamaño del texto<Pick value={String(data.prefs.textScale)} onChange={v=>pref({textScale:Number(v)})} label="Tamaño del texto" options={[{value:'1',label:'Estándar'},{value:'1.15',label:'Grande'},{value:'1.3',label:'Muy grande'}]}/></label><label className="switch-row"><span>Respuesta táctil<small>Vibración breve en dispositivos compatibles.</small></span><Switch checked={data.prefs.haptics} onCheckedChange={v=>pref({haptics:v})}/></label></section>
 <section className="setting-section reminders-section"><span className="setting-number">04 / NOTIFICACIONES</span><PeaceReminders data={data}/></section>
 </div>
 <div>
 <section className="setting-section privacy-section"><span className="setting-number">05 / PRIVACIDAD</span><ShieldCheck size={26} strokeWidth={1}/><h2>Un espacio privado.</h2><p>Tu Bitácora, proyectos y progreso se guardan en este navegador. En un dispositivo compartido, otras personas con acceso a este navegador podrían leerlos.</p><p>{protection.status==='unlocked'?'Los registros guardados están cifrados con tu frase. La app puede leerlos mientras está desbloqueada.':'El cifrado es opcional. Mientras no lo actives, los registros locales siguen siendo legibles.'}</p><p className="small muted">WARMA no elabora diagnósticos. El Espejo local no envía tu texto. El modo con IA, si está configurado, pide permiso antes de cada envío y no añade tu Bitácora ni evaluación.</p><LocalProtectionControls/></section>
 <section className="setting-section data-section"><span className="setting-number">06 / DATOS</span><h2>Tus datos son tuyos.</h2><p>Crea un respaldo para llevar tu mundo a otro dispositivo o recuperarlo si borras los datos del navegador.</p><div className="button-stack"><button className="btn secondary" onClick={()=>void act(downloadJSON)}><Download size={16}/>Exportar respaldo completo</button><label className="btn secondary file-label"><Upload size={16}/>Restaurar un respaldo<input type="file" accept="application/json,.json" className="sr-only" onChange={e=>{setRestore(e.target.files?.[0]||null);e.target.value='';}}/></label><button className="text-link danger-text" onClick={()=>setRemove(true)}><Trash2 size={16}/>Eliminar todos mis datos</button></div></section>
 <section className="setting-section"><span className="setting-number">07 / PWA</span><HardDrive size={26} strokeWidth={1}/><h2>Contigo, también sin conexión.</h2><p>{offlineReady?'La aplicación está preparada para abrirse sin conexión en este dispositivo.':'Abre la aplicación con conexión una primera vez para preparar los recursos sin conexión.'}</p><button className="btn secondary" onClick={onInstall}><Download size={16}/>Instalar WARMA</button></section>
 <details className="setting-section about-section"><summary>Dentro de WARMA</summary><p>Diseño, arquitectura y funcionamiento del proyecto.</p>{['WARMA','README','ARCHITECTURE','PWA'].map(f=><a className="doc-link" href={`/docs/${f}.md`} download key={f}>{f}.md <Download size={15}/></a>)}</details>
 </div>
 </div>
 <Confirm open={remove} onOpen={setRemove} title="¿Empezar con un nuevo mundo?" description="Se borrarán de este dispositivo todas tus reflexiones, proyectos, archivos, misiones y sesiones. Esta acción no se puede deshacer sin un respaldo." onConfirm={()=>act(resetWorld,'Tus datos se han eliminado de este dispositivo')}/>
 <RestoreBackupDialog file={restore} onClose={()=>setRestore(null)}/>
 </section>;
}
