'use client';
import PersonalizationNote from './warma-personalization';
import {plural,counted} from '@/lib/warma-copy';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Download,Palette,Sprout,Wind,Route,Feather} from 'lucide-react';
import {type WorldState,type Region,seeded,uid,mutateWorld,today} from '@/lib/itaca-store';
import {drawWarmaKnot} from '@/lib/warma-knot';
import {ViewHeading,act,formatDate,Pick} from './ui';

function GardenCanvas({data}:{data:WorldState}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;const render=()=>{const w=el.clientWidth,h=el.clientHeight,dpr=Math.min(devicePixelRatio,1.5);el.width=w*dpr;el.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const r=seeded(data.seed),completed=data.missions.filter(m=>m.done).length,pauses=data.wellbeing.pauses.length,sessions=data.sessions.length,count=Math.min(14,completed+pauses+sessions);const ground=h*.79;
 const halo=ctx.createRadialGradient(w*.5,h*.55,10,w*.5,h*.55,w*.45);halo.addColorStop(0,'#26594a55');halo.addColorStop(1,'#10252100');ctx.fillStyle=halo;ctx.fillRect(0,0,w,h);ctx.strokeStyle='#82b8a03b';ctx.beginPath();ctx.ellipse(w*.5,ground,w*.41,h*.075,0,0,7);ctx.stroke();
 const branch=(x:number,y:number,len:number,angle:number,depth:number,color:string)=>{if(depth<0)return;const xx=x+Math.sin(angle)*len,yy=y-Math.cos(angle)*len;ctx.strokeStyle=color;ctx.lineWidth=Math.max(.6,depth*1.4);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+Math.sin(angle)*len*.25,y-len*.65,xx,yy);ctx.stroke();if(depth===0){const g=ctx.createRadialGradient(xx,yy,0,xx,yy,7);g.addColorStop(0,'#d7edd2cc');g.addColorStop(1,'#6bc3ac00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(xx,yy,7,0,7);ctx.fill();return;}branch(xx,yy,len*.66,angle-.4-r()*.23,depth-1,color);branch(xx,yy,len*.62,angle+.4+r()*.23,depth-1,color);}
 if(!count){branch(w*.5,ground,28,0,1,'#86bdb1');}else for(let i=0;i<count;i++){const x=w*(.15+.7*(i+.5)/count),yy=ground+(r()-.5)*28,len=20+r()*30+Math.min(25,count*2),isPause=i<pauses;branch(x,yy,len,(r()-.5)*.3,2+Math.min(2,Math.floor(count/5)),isPause?'#86cdbb':'#c2c7a5');}
 const crystals=Math.min(24,new Set(data.wellbeing.pauses.map(p=>new Date(p.createdAt).toLocaleDateString('en-CA'))).size+data.projects.filter(p=>p.finished||p.tasks.length&&p.tasks.every(t=>t.done)).length);for(let i=0;i<crystals;i++){const x=w*.22+r()*w*.56,y=ground+15+r()*20;ctx.fillStyle=i%2?'#b1d8cc':'#cbd8b4';ctx.beginPath();ctx.moveTo(x,y-8);ctx.lineTo(x+4,y);ctx.lineTo(x,y+6);ctx.lineTo(x-4,y);ctx.closePath();ctx.fill();}};render();const ro=new ResizeObserver(render);ro.observe(el);return ()=>ro.disconnect();},[data]);return <canvas ref={ref} className="garden-canvas" role="img" aria-label={`Jardín de ${counted(data.wellbeing.pauses.length,'pausa','pausas')}, ${counted(data.sessions.length,'sesión','sesiones')} y ${counted(data.missions.filter(m=>m.done).length,'microacción','microacciones')}. No se marchita por inactividad.`}/>;}

export function Garden({data,navigate}:{data:WorldState;navigate:(r:Region)=>void}){const pauseDays=new Set(data.wellbeing.pauses.map(p=>new Date(p.createdAt).toLocaleDateString('en-CA'))).size;return <section className="workspace garden-view"><ViewHeading eyebrow="06 / JARDÍN BIOMÓRFICO" title="Lo que cuidas, crece." description="Las acciones y las pausas dejan una huella. Tu jardín te espera, sin perder nada cuando te alejas."/><PersonalizationNote data={data} place="garden"/><div className="garden-stage"><GardenCanvas data={data}/><div className="garden-caption"><span className="eyebrow">ECOSISTEMA PERSONAL</span><h2>{data.wellbeing.pauses.length+data.sessions.length?'Cada gesto deja una raíz.':'Todo empieza con una semilla.'}</h2><p>Crece con tus pausas, microacciones y sesiones.</p></div><div className="crystal-vessel"><span className="crystal-glyph" aria-hidden="true">◇</span><b>{pauseDays}</b><span>{plural(pauseDays,'cristal de pausa','cristales de pausa')}</span><small>Uno por día con una pausa.<br/>Sin rachas que perder.</small></div></div><div className="garden-ledger"><div><Wind size={20}/><b>{data.wellbeing.pauses.length}</b><span>{plural(data.wellbeing.pauses.length,'pausa','pausas')}</span></div><div><Route size={20}/><b>{data.missions.filter(m=>m.done).length}</b><span>{plural(data.missions.filter(m=>m.done).length,'microacción','microacciones')}</span></div><div><Sprout size={20}/><b>{data.sessions.length}</b><span>{plural(data.sessions.length,'sesión','sesiones')}</span></div><button className="text-link" onClick={()=>navigate('path')}>Regresar a mi camino <ArrowUpRight size={16}/></button></div><p className="small muted">Tus palabras privadas no otorgan puntos ni cristales. No hay rankings, penalizaciones ni comparaciones con otros estudiantes.</p></section>;}

export function RegulationObservatory({data}:{data:WorldState}){const [selected,setSelected]=useState(6);const days=Array.from({length:7},(_,i)=>{const day=new Date();day.setDate(day.getDate()-6+i);const key=day.toLocaleDateString('en-CA');return {key,label:day.toLocaleDateString('es-PE',{weekday:'short'}),focus:Math.round(data.sessions.filter(s=>new Date(s.createdAt).toLocaleDateString('en-CA')===key).reduce((n,s)=>n+s.seconds,0)/60),pauses:data.wellbeing.pauses.filter(p=>new Date(p.createdAt).toLocaleDateString('en-CA')===key).length,actions:data.missions.filter(m=>m.completedAt&&new Date(m.completedAt).toLocaleDateString('en-CA')===key).length};});const d=days[selected],max=Math.max(30,...days.map(d=>d.focus));return <section className="workspace regulation-observatory"><ViewHeading eyebrow="07 / OBSERVATORIO DE AUTORREGULACIÓN" title="Observa tu ritmo." description="Una mirada a tus hábitos para decidir qué mantener y qué ajustar."/><div className="rhythm-landscape"><div className="rhythm-head"><span className="eyebrow">ÚLTIMOS SIETE DÍAS</span><span>Enfoque y pausas · sin objetivos impuestos</span></div><div className="rhythm-columns">{days.map((day,i)=><button key={day.key} className={selected===i?'active':''} onClick={()=>setSelected(i)} aria-label={`${day.label}: ${counted(day.focus,'minuto de enfoque','minutos de enfoque')}, ${counted(day.pauses,'pausa','pausas')}`}><span className="rhythm-bar" style={{height:20+day.focus/max*160}}><i/>{day.pauses>0&&<em>{day.pauses}</em>}</span><span>{day.label}</span></button>)}</div><div className="day-detail"><span>{formatDate(d.key)}</span><strong>{d.focus}<small> {plural(d.focus,'minuto de enfoque','minutos de enfoque')}</small></strong><strong>{d.pauses}<small> {plural(d.pauses,'pausa','pausas')}</small></strong><strong>{d.actions}<small> {plural(d.actions,'paso completado','pasos completados')}</small></strong></div></div><div className="observation-notes"><article><span className="eyebrow">PREGUNTA PARA HOY</span><h2>¿Qué ritmo te resultó sostenible?</h2><p>Los espacios vacíos son días sin registros. No indican fracaso ni dicen cómo te sentiste.</p></article><article><span className="eyebrow">TU ÚLTIMO REGISTRO VOLUNTARIO</span><h2>{data.checkin?'Carga '+data.checkin.load:'Todavía sin registro.'}</h2><p>{data.checkin?`Energía ${data.checkin.energy} · ${formatDate(data.checkin.date)}. Puedes actualizarlo desde el inicio.`:'Puedes registrar cómo llegas desde el inicio, u omitirlo.'} Esto es autopercepción, no una medición clínica.</p></article></div></section>;}

export function EmotionArt({data}:{data:WorldState}){const [palette,setPalette]=useState<'lagoon'|'ember'|'dusk'>('lagoon'),[title,setTitle]=useState('Un espacio entre pensamientos'),[seed,setSeed]=useState(data.seed),[saved,setSaved]=useState(false);const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const draw=()=>{const w=c.clientWidth,h=c.clientHeight,d=Math.min(devicePixelRatio,1.5);c.width=w*d;c.height=h*d;ctx.scale(d,d);const bg=ctx.createLinearGradient(0,0,w,h),colors=palette==='ember'?['#301e26','#111f25']:palette==='dusk'?['#172434','#292232']:['#08242b','#132d2b'];bg.addColorStop(0,colors[0]);bg.addColorStop(1,colors[1]);ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);const r=seeded(seed);ctx.save();ctx.filter=palette==='ember'?'hue-rotate(135deg)':palette==='dusk'?'hue-rotate(55deg)':'none';drawWarmaKnot(ctx,w*.5,h*.49,Math.min(w*.22,h*.24),r()*.8,r()*5);ctx.restore();for(let i=0;i<20;i++){ctx.fillStyle='#cbe5d766';ctx.beginPath();ctx.arc(r()*w,r()*h,r()*1.5,0,7);ctx.fill();}};draw();const ro=new ResizeObserver(draw);ro.observe(c);return ()=>ro.disconnect();},[palette,seed]);
 const download=()=>canvas.current?.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='warma-composicion.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 return <section className="workspace art-view"><ViewHeading eyebrow="08 / ATELIER" title="Dale forma a este momento." description="Elige un color y una forma. Una expresión visual personal, sin interpretaciones sobre ti."/><div className="art-layout"><div className="art-print"><canvas ref={canvas} aria-label="Composición abstracta personal" role="img"/><span>WARMA / {title}</span></div><div className="art-controls"><Palette size={30} strokeWidth={1}/><label className="field-label">Nombre de esta composición<input value={title} maxLength={120} onChange={e=>{setTitle(e.target.value);setSaved(false);}}/></label><label className="field-label">Atmósfera<Pick value={palette} onChange={v=>{setPalette(v as typeof palette);setSaved(false);}} label="Atmósfera de la composición" options={[{value:'lagoon',label:'Laguna · verde mineral'},{value:'ember',label:'Brasa · tonos cálidos'},{value:'dusk',label:'Anochecer · azul profundo'}]}/></label><button className="btn secondary" onClick={()=>{setSeed(seed+1);setSaved(false);}}>Explorar otra forma <ArrowUpRight size={16}/></button><button className="btn primary" disabled={saved} onClick={()=>act(()=>mutateWorld(d=>{d.wellbeing.art.push({id:uid(),title:title.trim()||'Mi composición',seed,palette,createdAt:new Date().toISOString()});}),'Composición guardada').then(ok=>{if(ok)setSaved(true);})}>{saved?'Guardada':'Guardar composición'}<Sprout size={16}/></button><button className="text-link" onClick={download}>Descargar imagen <Download size={16}/></button><p className="small muted">Esta versión crea arte procedural en tu dispositivo. La generación por IA externa aún no está conectada. No analiza ni envía tus emociones.</p></div></div>{data.wellbeing.art.length>0&&<div className="art-history"><h2>Mis composiciones</h2>{data.wellbeing.art.slice(-8).reverse().map(a=><button key={a.id} onClick={()=>{setSeed(a.seed);setPalette(a.palette);setTitle(a.title);setSaved(true);}}><Palette size={18}/><span>{a.title}<small>{formatDate(a.createdAt)}</small></span><ArrowUpRight size={15}/></button>)}</div>}</section>;
}
